### ISSUE TITLE
Question about the deployment of the pruned model

### ISSUE THREAD

**Issue by cheerss** [he-y/filter-pruning-geometric-median#38]
Thanks for your great work. I wonder if I understand your algorithm well and my question is as follow:

As we all know, the number of output channels of some layers in resnet must be same because of the existence of residual block. 

Take resnet for cifar10 as example:

0. The number of output channels of block1 and conv0 are both 16. 
1. Assuming conv0 prunes the 1st, 2nd, 3rd channels (namely, the rest 13 channels are remained),.
2. Assuming block1/layer0 prunes the 4th, 5th channels (namely, the rest 14 channels are remained). 
3. Then when forwarding the model, we need to add the feature maps from conv0 and block1/layer0 all. The resulting feature maps still have 16 channels because conv0 and block1/layer0 prune different channels.

Does what I described above right?

If so, the deployed model still has to contain all zero weights, or I will not know which filters are pruned and how should I match features maps from conv0 and block0/layer1 when executing element-wise add operation.

Hopy for your reply!

**Comment by he-y** [comment]
Thanks for your interest.
Point 0,1,2 is right, and point 3 may not be right. This is because the **input** channel and **output** channel are different. 

Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-518118162) for the detailed dimension of pruned conv layers.
[This issue](https://github.com/he-y/filter-pruning-geometric-median/issues/28) may also help you with it.

To match the index, please take a look at my journal paper [Asymptotic Soft Filter Pruning for Deep Convolutional Neural Networks](https://ieeexplore.ieee.org/document/8816678):
![image](https://user-images.githubusercontent.com/10541284/66986976-6a703080-f0f2-11e9-9eeb-c2b9dcf7f924.png)

**Comment by pyt1234** [comment]
> Thanks for your interest.
> Point 0,1,2 is right, and point 3 may not be right. This is because the **input** channel and **output** channel are different.
> 
> Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-518118162) for the detailed dimension of pruned conv layers.
> [This issue](https://github.com/he-y/filter-pruning-geometric-median/issues/28) may also help you with it.
> 
> To match the index, please take a look at my journal paper [Asymptotic Soft Filter Pruning for Deep Convolutional Neural Networks](https://ieeexplore.ieee.org/document/8816678):
> ![image](https://user-images.githubusercontent.com/10541284/66986976-6a703080-f0f2-11e9-9eeb-c2b9dcf7f924.png)

@he-y When the Conv3 on Fig.4 output feature maps with 128 channels and the skip branch is with 256 channels, how did you make the summation? 

I think your implementation is problematic? And also the figure in your paper. Ref #23
