### ISSUE TITLE
Is it reasonable to get zero filters larger than the  theoretical pruned num?

### ISSUE THREAD

**Issue by workingBird926** [he-y/filter-pruning-geometric-median#42]
Thanks a lot for your great work! 
When I run the code, I have met some problems in getting the small model, and I have tried to find the reasons.
As described in the issue:Is it reasonable to get zero filters larger than the  theoretical pruned num? e.g the filter num in first conv is 64, the pruned rate is 0.3, so, the theoretical pruned num is 45,  but I got 50 zero filters. Is it reasonable？
This problem caused the failure in getting the small model because the kept filters num may not equal to the theoretical value. To get the small model successfully, I have to pick some zero filters as the kept filters, which leads to the precision decrease in the small model. 
During reading your code, it seems that the zero filters should be equal to the theoretical num, I am not clear if it is right?

**Comment by he-y** [comment]
Thanks for your interest.
The "get_small" function obtains the channel number based on the real model, instead of the "theoretical pruned num", please take a look at [these codes](https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py#L244-L249).
So you can set any pruning ratio regardless of the "theoretical pruned num".
