### ISSUE TITLE
Same accuracy between val_acc_1 and val_acc_2

### ISSUE THREAD

**Issue by EdwardLiuYu** [he-y/filter-pruning-geometric-median#56]
Hello, I run your code on Resnet18. The log file show that the accuracy before and after pruning is the same. Could you explain the reason.
![image](https://user-images.githubusercontent.com/44216841/81395582-7c7cf380-9156-11ea-8950-7c5ddd3b44c8.png)

**Comment by EdwardLiuYu** [comment]
I don't know why after training process your pruning method doesn't cause accuracy change, but in Soft Filter Pruning the accuracy is changed after init_mask and do_mask

**Comment by he-y** [comment]
Yes. It's because the gradients are set to zero, please take a look at [code](https://github.com/he-y/filter-pruning-geometric-median/blob/44030b7befce47b3c59f708dfe546a92c841765d/pruning_cifar10.py#L313).

This is because we want to remove the effect of "Soft Filter Pruning", and see the power of "geometric median".

**Comment by DavidYanAnDe** [comment]
Could you please describe in more detail why the precision is the same? I don't quite understand your explanation. If set the grad = 0, then the foreward process won't consider the filter whose grad = 0, so that the acc won't change?
